### PR TITLE
rename `Visual Studio Team Services` to `Azure Pipelines`

### PR DESCRIPTION
**Pull request by travi**
since the service itself was rebranded:
https://azure.microsoft.com/en-us/blog/introducing-azure-devops/

BREAKING CHANGE: the `vsts` service name is now `azurePipelines`

### CODE REVIEW

**Comment by travi** [comment]
Hi @pvdlg 👋🏼 

I've been having to work with Azure DevOps in a new role. Not being familiar with ADO previously, I wasn't aware that it was a branding change from VSTS. Therefore, it took me a bit to realize that Azure DevOps was included in the supported CI list. Hoping this makes it more obvious for someone in the future.

I did notice that none of the other service names used a `-`, but it seemed appropriate here. If you'd prefer a simpler option, I'm happy to update.

**Comment by gr2m** [comment]
@travi shall we apply the change with the next breaking release?

**Comment by gr2m** [comment]
> works for me. however, this seems separate enough from the switch to ESM that i wonder if we should release this separately/before the ESM changes

good point, I don't mind at all

> what thoughts do you have around naming conventions used in this change? i was a bit on the fence around what i went with and i wonder if [#156 (comment)](https://github.com/semantic-release/env-ci/pull/156#discussion_r735635132) sets a new precedent that should be followed with this change

could catch! We should probably document the service naming conventions in the README and in a comment above the export in `index.js`?

**Comment by travi** [comment]
i updated to follow the convention set in the cloudflare pages PR. i think having multiple examples makes the convention clear enough without a comment, but you could convince me that it is worth adding one. previously, there just wasnt an example to follow since all services had simple names.

**Comment by gr2m** [comment]
> i think having multiple examples makes the convention clear enough without a comment

yeah I think we should be good. Time will tell, it's a problem when it's a problem.

Do you want to go ahead and release v6 without the ESM transition? Feel free to do so

**Comment by travi** [comment]
> Do you want to go ahead and release v6 without the ESM transition?

yeah, i think it makes sense to make this available ahead of the esm transition so that folks arent blocked migrating to use is by other details that might block them from transitioning to consuming an esm-only package

**Pull request merged**
